### ISSUE TITLE
Complemented character sets not working with orderless-regexp

### ISSUE THREAD

**Issue by hmelman** [oantolin/orderless#104]
Do complemented character sets work?  I want to match all lines not containing several letters.  

Since I use a prefix of `!` to mean `orderless-without-literal` I could do:

    !a !s !d !f

But I'd rather do:

    [^asdf]

But it doesn't seem to work.  I'm using it with `consult-keep-lines` and regular character sets like `[asdf]` work as expected.  I have:

          (setq orderless-matching-styles '(orderless-literal orderless-regexp))

**Comment by oantolin** [comment]
The regexp `[^asdf]` matches any line containing at least one character that is not `a`, `s`, `d` or `f`; for example the line `soda fountain` matches because `o` is not among `a`, `s` `d` or `f`.

If you want to match lines without `a`, `s`, `d` or `f`, you need to say "the line is made up entirely of non-`asdf` characters", like this `^[^asdf]*$`.

**Comment by minad** [comment]
See also #88. Maybe you want sth like `![asdf]`?

**Comment by oantolin** [comment]
A general `orderless-without-regexp` sounds like more trouble than its worth, but adding support for character ranges would be pretty easy.

**Comment by minad** [comment]
@oantolin I agree and I am not in favor of adding #88. I wonder if one could define a restricted useful subset.

**Comment by hmelman** [comment]
For now, I've added the following to the `cond` in my dispatcher and it seems to work.

```elisp
   ;; ![chars] is a complementary character set as: ^[^chars]*$
   ((and (string-prefix-p "![" pattern) (string-suffix-p "]" pattern))
    `(orderless-regexp . ,(concat "^[^" (substring pattern 2 -1) "]*$")))
```

**Comment by oantolin** [comment]
@hmelman Cool!

**Comment by hmelman** [comment]
I'm debating if instead of `![chars]` I should just use `[^chars]`.  It makes the latter behave as I expected.  It does lose its existing value as regexp, but I think I'm okay with that.  Can you think of use-cases where it would be useful?  None are coming to me.

**Comment by oantolin** [comment]
Just `[^chars]` on its own? No, I don't think I'd ever use that. The one thing that would keep me from using such a dispatcher is discontinuity: `[^chars]` would abruptly mean something different when you add more text right after the `]`, since then it would go back to being interpreted as a regexp.

**Comment by hmelman** [comment]
The discontinuity you mention applies equally well to `![chars]` if you add text after the `]`.  I get that it seems odd, but it also seems like a decent dwim hack.  Unless I'm missing another use case.

**Comment by oantolin** [comment]
> The discontinuity you mention applies equally well to `![chars]` if you add text after the `]`.

True! I hadn't noticed that.

I think your `[^chars]` wouldn't actually cause you any trouble (specially if your dispatcher has any syntax for forcing regexp interpretation), but only using it for a while will tell.

**Comment by hmelman** [comment]
For now I have both in, we'll see what works.  Thanks.
