### ISSUE TITLE
I can't get the suggsted configuration for integration with Company to work.

### ISSUE THREAD

**Issue by JonatanSahar** [oantolin/orderless#126]
I've tried to change the separator as shown in the example in the documentation, but hitting `&` is still being considered as part of the string to complete, and causes the popup to close (since there's obviously no completion available with `&` in the middle of the word..)
Can you advise?
Thanks!

**Comment by minad** [comment]
Orderless support in Company is highly dependent on the backend. Which one do you use? It would be ideal if you paste a minimal configuration which shows the issue.

(You could also give my Corfu package a try as an alternative to Company. It has been designed with better Orderless support in mind and has other advantages. However it may be a bit too much to ask to switch the UI if you are happy with your overall completion setup via Company.)

**Comment by JonatanSahar** [comment]
Hi, 
Thanks your response!
I have the following value for `company-backends`:
`(company-capf
 (:separate company-dabbrev company-yasnippet company-ispell))
`

I'll try to work out a workable minimal config later today.
Thanks again.

**Comment by minad** [comment]
A minimal config would be good to have. But to be clear - the only backend included should be company-capf since this is the only one which can use Orderless. Which capf do you use, lsp-mode, eglot, elisp, ...?

In case you recall the specific issues you had with Corfu I would be interested in hearing them. The package changed quite a bit in recent months so it may be better now. On the other hand some backend issues may still not be fixed - this is not in my hands. Corfu grew out a bit out of my personal frustration with the complexity of Company (intermediate backends, company-capf and the lack of integration in Emacs). My personal Corfu configuration is quite simple (like the one from the README) and just works.

**Comment by minad** [comment]
I think this issue can be closed since it is quite old, with no further response. Company support for completion styles is limited (only company-capf and company-dabbrev) and Company isn't prepared to work with component-based Orderless completion. I suggest to ask Company-specific questions on the Company discussion forum.
