### ISSUE TITLE
No highlighting in company popup

### ISSUE THREAD

**Issue by noctuid** [oantolin/orderless#14]
I'm opening an issue here first because I'm not sure whether company is actually at fault or not. If I set `completion-styles` to `'(flex)`, for example, it shows the highlighting correctly in the company popup, but for orderless, there is no highlighting.

**Comment by oantolin** [comment]
Oh. I'll read the flex source code to se how they do it.

**Comment by oantolin** [comment]
Mmh. It looks like company is specifically looking for the face `completions-common-part`... :( (And changing `orderless` to use only that face does make the highlighting appear in company.)

I'll think about detecting use through company and in that case using only that face. But maybe company should actually allow more than one face for higlighting matches.

**Comment by oantolin** [comment]
So, from reading company's source, it seems it only supports using one face for highlighting matches. A company backend can provide a `match` operation that computes a list of intervals to highlight and they always get highlighted with the `company-echo-common` face.

Now, how does company wind up using `completions-common-part` then? Well, company comes with a `company-capf` backend that uses the standard capf (completion at point functions) API, capf in turn uses completion styles. The company-capf backend's implementation of `match` goes through the candidates and searches for the `completions-common-part` face, and returns those intervals. At some point later company applies `company-echo-common` to those intervals.

In other words, you can't get easily get company to whatever the faces the completion style wants: company-capf will take of note of where it finds `completions-common-part` and then in a separate step apply to those intervals the only face it uses to highlight matches, `company-echo-common`.

So I think if people want more faces in company, company needs to change (for example, the `match` operations could be generalized: instead of just returning a list of intervals, it could be allowed to return a list of intervals with faces for each). Maybe it's reasonable to propose that over at company.

In the meantime, if you are satisfied with highlighting all matching portions with the same face, you can use this:

```elisp
(defun orderless--use-completions-common-part (fn &rest args)
  (let ((orderless-match-faces [completions-common-part]))
    (apply fn args)))

(advice-add 'company-capf--candidates
            :around #'orderless--use-completions-common-part)
```

I think I'll add the function to `orderless` and add the `advice-add` call to the README in a new integration with company section.

**Comment by oantolin** [comment]
I've added a section to the README on Company integration now. I think that's really all that can be done on this end for the highlighting. Maybe we can close this issue.

**Comment by noctuid** [comment]
Okay, I opened an issue on the company repo. Thanks for the workaround.
