### ISSUE TITLE
Case sensitive matching

### ISSUE THREAD

**Issue by saolaolsson** [oantolin/orderless#140]
Would it be possible to support case sensitive matching using style dispatchers? As far as I can tell, it's not currently possible, but such a solution would be more flexible than toggling `completion-ignore-case` manually.

I am aware of `orderless-smart-case` but as all "smart case" solutions it doesn't work when the thing you're interested in is all lower case.

**Comment by oantolin** [comment]
You could do something like this

```elisp
(defun case-dispatcher (target _index _total)
  (when (equal "&&" target)
    (setq-local orderless-smart-case nil completion-ignore-case nil)
    '(orderless-literal . "")))

(add-to-list 'orderless-style-dispatchers #'case-dispatcher)
```

Then, whenever you toss in a component that is `&&` the matching turns case sensitive (even if you delete the `&&`) for the rest of the current minibuffer session.

**Comment by oantolin** [comment]
I can't add a mechanism to control case sensitivity on a per-component basis and keep the core design (which is to just lexically bind `completion-regexp-list` and let Emacs do its thing). So the best that could be done is to control this on a per-session basis and as illustrated above that can already be done (one could add the option to turn it case-sensitivity back off, for which I'd suggest a single `&`, so that deleting one of the two `&` does it) in user configuration code. So I'm closing as this seems to require no changes in orderless, but feel free to continue the discussion.

**Comment by minad** [comment]
As a better alternative to your example above one can probably define a custom pattern compiler which either sets or unsets completion-ignore-case depending on the presence of &&, such that it won't affect the session forever?

**Comment by oantolin** [comment]
Yes, one could. But you can also make that same style dispatcher turn off case sensistivity when given a single `&`. That way to turn it off again you just delete a `&` (or both).

**Comment by saolaolsson** [comment]
It appears style dispatching is more flexible than I thought. This'll work fine for my needs. Thank you!
