### ISSUE TITLE
Warning: Value for ‘orderless-matching-styles’ does not match type hook

### ISSUE THREAD

**Issue by uqix** [oantolin/orderless#157]
To reproduce:

* Emacs version: 29.2
* orderless version: 20231110.1448
* Init config:

```emacs-lisp
(setopt orderless-matching-styles
        (list #'orderless-literal #'orderless-regexp))
```

Warning on startup:

> Warning (emacs): Value ‘((orderless-literal orderless-regexp))’ for ‘orderless-matching-styles’ does not match type hook

**Comment by oantolin** [comment]
That error sounds like you are running `setopt` before orderless is loaded. Before orderless is loaded,  `orderless-literal` and `orderless-regexp` do not denote functions yet, they are just symbols, so the warning is correct: you are setting `orderless-matching-styles` to a list of symbols, not a list of symbols that are function name (which would be acceptable for a hook).

There are two ways to solve this: either run the `setopt` after loading orderless (for example, by putting in an `(with-eval-after-load 'embark ...)` form); or change `setopt` to `setq` (because `setq` trusts you know what your are doing).

Please let me know if neither of those solutions worked for you.

**Comment by uqix** [comment]
`setopt` after `require` fixes the issue, thanks.
