### ISSUE TITLE
consult-locate not supported Chinese Pinyin first letter search 

### ISSUE THREAD

**Issue by 1925381584** [oantolin/orderless#172]
hi,when I set like below, consult-buffer can supported chinese pinyin first letter search, but consult-locate does not take effect.
Can you see what the problem is

(defun orderless-regexp-pinyin (str)
  (setf (car str) (pinyinlib-build-regexp-string (car str)))
  str)
(advice-add 'orderless-regexp :filter-args #'orderless-regexp-pinyin)

**Comment by minad** [comment]
Maybe you want to use Orderless also as pattern compiler for consult-grep etc? See https://github.com/minad/consult/wiki#use-orderless-as-pattern-compiler-for-consult-grepripgrepfind. 

However `consult-locate` is a special command since locate does not necessarily understand regular expressions, since these won't work efficiently with the locate database index.

**Comment by 1925381584** [comment]
yes, as you say, first locate database index need support Chinese Pinyin first letter search,if it don't support, when you send "nh" to locate, it can't answer you "你好"

**Comment by minad** [comment]
I just took another look at `consult--locate-builder`. This function builds the locate command line, splits the input argument and then **passes the input unmodified to locate**, because of what I wrote above about the database index. Integrating Pinyin is therefore not supported, but it may be possible to override the function with one which transforms the input first. I close this issue, since it is not an Orderless issue.
