### ISSUE TITLE
Smart case

### ISSUE THREAD

**Issue by noctuid** [oantolin/orderless#18]
Not sure if this is feasible, but it would be nice if there was a way to have smart case support or at least to support the equivalent `case-fold-search`.

**Comment by oantolin** [comment]
`case-fold-search` makes search case insensitive, right? `orderless` already obeys the standard `completion-ignore-case` variable.

**Comment by noctuid** [comment]
> orderless already obeys the standard completion-ignore-case variable.

Thanks for pointing me to this. Would be nice if smart case ("i" matches "i" and "I", "I" matches only "I") was a possibility, but maybe that is outside the scope of this packaage.

**Comment by noctuid** [comment]
I guess one way I could do this is to advise `orderless-default-pattern-compiler` to set `completion-ignore-case` based on whether the pattern contains any capital letters. And then I could maybe advise `completing-read` to let bind `completion-ignore-case` to prevent this from affecting the global value. Do you have any ideas for a better method?

**Comment by oantolin** [comment]
I think it worth adding directly to `orderless`. Let's just think about what the best behavior and interface is.

You described smart case as meaning "i" matches "[iI]" and "I" matches "I". I don't think any commands in Emacs behave in that way. The other behavior you mentioned in your last comment I think is what `isearch` does by default:

- if there are only lowercase letters in the search string, then matching is case insensitive
- if there is any uppercase letter at all, then matching is case sensitive.

The difference is that with you first description "It" would match "I[tT]", but what isearch does is have ti match "It".

I think the isearch thing is probably the behavior we should go for: it will be familiar to users _and_ as a bonus, is easier to implement (with your strategy of locally binding `completion-ignore-case`).

Now, for the interface to activate this, how about using the same `search-upper-case` variable that isearch uses? Or, if that's too sneaky, we can add a new `orderless-search-upper-case` variable (I don't like the name that much, but since isearch uses it I feel it is "standard").

**Comment by oantolin** [comment]
Mmh, maybe the least confusing way is a new `orderless-smart-case` variable. When `t` it overrides `completion-ignore-case` (and `read-file-name-completion-ignore-case`, `read-buffer-name-completion-case`, too), when `nil` those variables are respected.

**Comment by oantolin** [comment]
I implemented this (with an `orderless-smart-case` variable) in the smart-case branch (bc9e482). Please test and read the docstring for the new variable to make sure it is clear.

**Comment by noctuid** [comment]
> I think the isearch thing is probably the behavior we should go for

Yes, this is the behavior I want. I just described it badly at first.

> I implemented this (with an orderless-smart-case variable) in the smart-case branch (bc9e482). Please test and read the docstring for the new variable to make sure it is clear.

Thanks! It works as expected for me, and the documentation is clear.

**Comment by oantolin** [comment]
Excellent, I will merge this into master and tag a release for MELPA stable.
