### ISSUE TITLE
Out-of-order fails when `completing-read` has initial input

### ISSUE THREAD

**Issue by protesilaos** [oantolin/orderless#3]
When `completing-read` is given an initial input, such as one that represents a directory path, out-of-order matching will yield no results, _unless the user's input starts with a space_.

```elisp
(find-file
 (completing-read "Open recentf entry: " recentf-list nil t "/home/prot/"))
```
So If I evaluate the above and immediately type `the mo` I am getting no matches.  But if I type `SPC the mo` I am getting a list of candidates.

![Screenshot at 2020-04-14 08-21-07](https://user-images.githubusercontent.com/12828033/79188906-02906d80-7e29-11ea-9686-a2bc1448198d.png)

![Screenshot at 2020-04-14 08-21-32](https://user-images.githubusercontent.com/12828033/79188914-06bc8b00-7e29-11ea-96d3-80dce5c506ee.png)

Would it be possible to account for initial input and assume a space?

**Comment by protesilaos** [comment]
Of notice is also the fact that Icomplete no longer highlights the matching characters (beside the matching candidate), but we can check that later.

**Comment by oantolin** [comment]
I thought the `completion-boundaries` function had my back for this initial input business. I guess not, or rather, not in all cases, because it certainly fixed issue #1.

**Comment by oantolin** [comment]
> Of notice is also the fact that Icomplete no longer highlights the matching characters (beside the matching candidate), but we can check that later.

Yes, that's issue #4, kindly submitted by @jixiuf.

**Comment by oantolin** [comment]
> When completing-read is given an initial input, such as one that represents a directory path, out-of-order matching will yield no results, _unless the user's input starts with a space_.

I don't think this is actually true. What I think is going on in your image is that `/home/prot/the` is being taken as a single regexp and it doesn't match any candidate. If, instead of `the mo`, you had typed `G the mo`, for example, it would use regexps `/home/prot/G`, `the` and `mo`, and some candidates do match all three. That would happen _even though you started with `G` and not with a space_.

So, I think it's working as advertised, so maybe this isn't technically a bug. It can be inconvenient, though, and we can try to fix it. Let me think about it a bit.

**Comment by oantolin** [comment]
Maybe a good solution is to have the regexp separator configurable. For completing paths you'd want to split the pattern on whitespace _and_ slashes.

**Comment by oantolin** [comment]
i just realized the separators are already configurable. :) You can wrap your `completin-read` call in:

```elisp
(let ((split-string-default-separators "[/ ]"))
   ...)
```
to have both slashes and spaces separate the regexps.

**Comment by protesilaos** [comment]
You are right, this is not a faulty behaviour per se. Just a matter of easing the user experience.

With regard to `split-string-default-separators`, it does indeed work. Could this be exposed as a user-facing option for when orderless is being used?

**Comment by oantolin** [comment]
I was first inclined to just document the usage `split-string-default-separators`, but I decided to add a variable `orderless-regexp-separator`, mostly because I think people might want to change its value for their entire Emacs session, and it seems like a terrible idea to fiddle with `split-string-default-separators` (as it affects every call to `split-string` which does not specify a separator).

Does adding that option adequately address this issue?

**Comment by protesilaos** [comment]
Yes, I can confirm this works!

**Comment by oantolin** [comment]
Excellent, I'll close this issue then.
