### ISSUE TITLE
Idea for easy configuration

### ISSUE THREAD

**Issue by astoff** [oantolin/orderless#31]
Clearly orderless is configurable to a pretty much arbitrary degree... if you are willing to deal with minibuffer hooks and what not.

Now, suppose I wanted to use a particular value of `orderless-matching-styles` for a particular class of commands, say just `'(orderless-regexp)` for `consult-lines` and friends (because `orderless-initialism` is too permissive when matching against whole lines of text).  How would you do it?  I think it would be neat if a configuration like this worked:

``` elisp
(setq completion-category-overrides
      '((file (styles partial-completion))
        (consult-location (orderless-matching-styles orderless-regexp))
                          (orderless-style-dispatchers first-initialism
                                                       flex-if-twiddle
                                                       without-if-bang)))
```

**Comment by oantolin** [comment]
It's a good idea to have per category configuration for orderless (at least for Marginalia and Consult users, who actually do have plenty of categories they work with), but I think orderless should have its own variable for that rather than abusing completion-category-overrides (which would confuse the minibuffer).

**Comment by oantolin** [comment]
I like this idea!

**Comment by astoff** [comment]
Sure, it could be a variable in the orderless namespace, even though the docstring of `completion-category-overrides` kind of suggests it can be used to convey any property of the completion style.

**Comment by oantolin** [comment]
I deleted that earlier comment about making this a variable specific to orderless, because I was confused when I wrote it. I misremembered the format of `completion-category-overrides`, I thought is was an alist of categories and lists of completion styles, but it's actually an alist of categories and alists, whose `styles` key should be associated to a list of completion styles (as seen in your example). So this would work, orderless can definitely use it's own keys as you suggest.

**Comment by oantolin** [comment]
Done, please test!

**Comment by astoff** [comment]
Works nicely! So you don't want to suggest people to set their `completion-category-defaults` to nil?

**Comment by oantolin** [comment]
I guess I probably should mention `completion-category-defaults`.

**Comment by oantolin** [comment]
Done. 4844452f4e7008da2ebe96c7dbbb7bcd655bbe68

**Comment by oantolin** [comment]
Whoops, I accidentally removed the overview in that commit. 😆 I brought it back now.

**Comment by oantolin** [comment]
Hi, @astoff. I've reverted this change because of what @minad explains in #33. Particularly this comment:

> When I look at completion-all-completions and completion--nth-completion the complete metadata handling already happens there. It looks like you don't have access to the completion category in the completion style itself. This is by design. By accessing the minibuffer-completion-table from your pattern compiler you violate this design and the assumptions. For example by consult--default-completion-filter will not work, since it explicitly passes metadata, as is allowed by the completion-all-completions API.

**Comment by oantolin** [comment]
So @minad suggested we instead make it easy for people to define their own completion styles which are pre-configured versions of orderless. Those completion styles can easily be put in `completion-category-overrides`.

**Comment by oantolin** [comment]
I like that idea and suggested we do it on the cheap:

```elisp
(defmacro orderless-define-completion-style (name &rest configuration)
  "Define a orderless completion style with given CONFIGURATION.
The CONFIGURATION should be a list of bindings that you could use
with `let' to configure orderless.  You can include bindings for
`orderless-matching-styles' and `orderless-style-dispatchers',
for example.

The completion style consists of two functions that this macro
defines for you, NAME-all-completions and NAME-try-completion.
This macro registers those in `completion-styles-alist' as
forming the completion style NAME."
  (let ((all-completions
         (intern (concat (symbol-name name) "-all-completions")))
        (try-completion
         (intern (concat (symbol-name name) "-try-completion"))))
  `(progn
     (defun ,all-completions
         (string table pred point)
       (let ,configuration
         (orderless-all-completions string table pred point)))

     (defun ,try-completion
         (string table pred point)
       (let ,configuration
         (orderless-all-completions string table pred point)))

     (add-to-list 'completion-styles-alist
                  '(,name ,try-completion ,all-completions)))))
```

**Comment by minad** [comment]
Can I attach custom dispatchers to `orderless-define-completion-style` as I proposed in #33?

**Comment by oantolin** [comment]
You could do this:

```elisp
(defcustom my-dispatchers-for-style-foo '(default dispatchers for foo))

(orderless-define-completion-style foo (orderless-style-dispatchers my-dispatchers-for-style-foo))

;;; some time later

(setq my-dispacthers-for-style-foo '(different dispatchers))
```

**Comment by minad** [comment]
Okay, I like it! I like in particular that the macro `orderless-define-completion-style` is independent from the rest. We do not touch anything else and get the same benefits as with the original proposal, right? 

I only wonder about the "default" orderless style. Should this also be defined via `orderless-define-completion-style`? I would prefer that if it is possible, since it would put the default style on an equal footing as custom defined styles.

**Comment by oantolin** [comment]
> Okay, I like it! I like in particular that the macro `orderless-define-completion-style` is independent from the rest. We do not touch anything else and get the same benefits as with the original proposal, right?

I think so, yes.
 
> I only wonder about the "default" orderless style. Should this also be defined via `orderless-define-completion-style`? I would prefer that if it is possible, since it would put the default style on an equal footing as custom defined styles.

I don't see any advantage to defining the default style with this macro. I mean these defined styles just wrap the default style in a let.

**Comment by oantolin** [comment]
I guess the macro should let you specify docstrings for the generated functions and for the generated completion style.

**Comment by oantolin** [comment]
This just seemed like the laziest possible way of defining new completion styles that are differently-configured versions of orderless.

**Comment by minad** [comment]
> I don't see any advantage to defining the default style with this macro. I mean these defined styles just wrap the default style in a let.

It is more of a stylistic thing. But having derived styles like this is acceptable too. As I said I like very much that everything is nicely independent of the rest and the newly defined styles will be more easily reusable than in the original proposal.

> I guess the macro should let you specify docstrings for the generated functions and for the generated completion style.

Agree.

> This just seemed like the laziest possible way of defining new completion styles that are differently-configured versions of orderless.

Yes and I think it is even good :laughing:

**Comment by oantolin** [comment]
OK, I've added the macro, it takes a non optional argument which is a possibly empty list of docstrings. Not sure that's the best interface.

**Comment by minad** [comment]
What about only taking a single string for the style description and for the functions generate a simple docstring, which references the documentation of `orderless-all-completions`/`orderless-try-completions`? I think that is sufficient.

**Comment by oantolin** [comment]
Sounds better! But what would the docstrings for the functions say exactly? They could be identical to the docstring for orderless-all-acompletions except for the last sentence where I replace `orderless` with the name of the new style.

**Comment by minad** [comment]
I would just write something along the lines of "all-completions function of the style <name> derived from `orderless`, see `orderless-all-completions` for details."

**Comment by oantolin** [comment]
OK, but I'd add it is part of the NAME completion style, too.

**Comment by oantolin** [comment]
OK, how's this? 94d52640d4d8eed1a412907a4e4b6d4dea990b7f

**Comment by astoff** [comment]
I didn't get the chance to read this all carefully, but it seems that the new approach, while totally reasonable, doesn't cater for the use-case of my original comment, since the `styles` entries of `completion-category-overrides` just _add_ to the default styles. This can be changed by hacking `completion--styles`. It would seem reasonable to change Emacs so that the merging of styles doesn't happen if the `styles` entry ends with some special value, say `nil`.

**Comment by oantolin** [comment]
> since the `styles` entries of `completion-category-overrides` just _add_ to the default styles.

This is true, but I still think this is good enough for your use case. The added styles get tested *first*, so, as long as you type something that does match the style you added to `completion-category-overrides`, that's the style that gets used.

Why do you want no further styles to be used in case the overriding style does not match?

**Comment by astoff** [comment]
In the particular case of `consult-lines`, it's nice to filter things out more aggressively, in exchange for typing a more specific query.

Ah, wait, is the falling back to next style global or on a per-entry basis?

**Comment by oantolin** [comment]
> Ah, wait, is the falling back to next style global or on a per-entry basis?

I don't quite understand the way you are phrasing the question @astoff, so I won't answer either "global" or "per-entry", since I wouldn't be sure what I was claiming. :P

Every time a completion is attempted (with a continously updating completion UI like Selectrum or Icomplete, this is done for every keystroke), several completion styles are tried in order until one returns a non-nil list of completions. First the completion styles in `completion-category-overrides` for the current category are tried in order, next the completion styles in `completion-category-defaults` for the current category are tried in order, and finally the styles in `compeltion-styles` are tried in order.

So, for example, consider the following configuration:

```elisp
(setq completion-styles '(orderless)
      orderless-matching-styles '(orderless-regexp orderless-flex)
      orderless-style-dispatchers nil)

(orderless-define-completion-styles just-regexp
  (orderless-matching-styles '(orderless-regexp)))

(setf (alist-get 'consult-location completion-category-overrides)
      '(styles just-regexp))
```

What happens when using `consult-line` is that as long as what you type matches at least one line with all components matching as regexps, then you only see regexp matches from the just-regexp style; but if your query fails to match in that style, then you would see matches where some components match in the flex style and the rest match as regexps.

Is that good enough, or would you really want to avoid seeing any flex matches at all? I think in practice it's not hard to ensure what you type matches at least one thing in the overriding style, so I don't mind the fallback for the case of 0 matches in the overriding style.

**Comment by clemera** [comment]
@astoff Maybe you would also be happy with using `orderless-transient-matching-styles`, you can set the styles locally in minibuffer-setup-hook do adjust the styles for the current session. @oantolin I just noticed that `orderless-remove-transient-configuration` could be removed. As we discovered since when they were introduced local vars need not to be cleaned up manually after minibuffer sessions.

**Comment by minad** [comment]
@clemera @oantolin Why are these orderless-transient variables even there? Can they not be replaced by simple local overrides of the corresponding variables?

**Comment by clemera** [comment]
@minad I think you right, usually setting `orderless-matching-styles` locally should be enough, maybe we missed that back then.

**Comment by minad** [comment]
@clemera I made a separate issue for that #34.

**Comment by astoff** [comment]
Thanks, this looks great (if slightly less nice than the original wish :stuck_out_tongue_closed_eyes:).

**Comment by oantolin** [comment]
I'll close this issue, but feel free to reopen or open a new one if this solution proves inadequate.
