### ISSUE TITLE
Try the longest common substring for `try-completion'?

### ISSUE THREAD

**Issue by JSDurand** [oantolin/orderless#32]
Currently "orderless-try-completion" does not try to complete the input when it matches more than one candidate. I think it could be useful to have this feature, so I have written a little package to find the longest common substrings(s) of multiple strings using Ukkonen's algorithm for building generalized suffix trees. The repository is here: https://gitlab.com/mmemmew/suffix-tree

I am wondering about your opinions. Do you think it would be a useful feature to add?

**Comment by oantolin** [comment]
I never added something like this because I am under the impression it is impossible to know what to do with the longest common substring, that it is impossible to figure out how to modify the user's query in general.

For example, say you do compute the longest common substring, what do you do with it in the following cases?

1. The user has `(setq orderless-matching-styles '(orderless-initialism))`.
   
2. The user has a configuration of style dispatchers where every component needs a one character prefix to indicate the type, say `L` for literals, `R` for regexps, `I` for initialism, etc. How would the could know that this is what the user is doing, and how would it figure out what user-chosen prefix it needs to add?
   
3. The user wrote their own `orderless-pattern-compiler` that has a completely different syntax, maybe s-expressions like `(and (literal "hello") (initialism "abd"))`.
   
So I think the feature you are proposing is literally impossible to implement, but if you have a concrete proposal we can discuss it further.

**Comment by JSDurand** [comment]
Thanks for the quick and thoughtful reply.

I proposed this feature based upon the following assumption.

> When the user chooses to press TAB to try-completion, the user just wants to transform the input into a candidate.

This assumption is not always valid, so I am thinking about maybe an option to toggle the behavior?

If this assumption is valid (chosen by a user), then try-completion can simply replace the user input with the longest common substring (or the "maximal" common substring in the sense that any common substring is also a common substring of this string). Currently my little package only offers the longest common substring, but it is not hard to write a function to return the "maximal" common substring.

(In categorical terms, the "maximal" common string is the product of the strings in the category of strings where a morphism is an embedding of one string into a substring of another.)

**Comment by oantolin** [comment]
That's not the only assumption you made, you also seem to be assuming that the longest common substring will match some candidates! If often doesn't match anything at all!

That's why I gave you those examples. Take the first one: if the user is currently only using the initialism matching style and you insert the longest common substring it will almost certainly match nothing. To be super concrete, say you are in `describe-function`, using *only* intialism matching and you type `flol`. In my Emacs that matches only: 

- `font-lock-turn-on-thing-lock`, and
- `font-lock-turn-off-thing-lock`.

The longest common substring is `font-lock-turn`. If `TAB` replaced `flol` with `font-lock-turn`, then nothing would match any more, because there is no command with initials `f`, `o`, `n`, `t`, `-`, `l`, `o`, `c`, `k`, `-`, `t`, `u`, `r`, `n`. The maximal common substring, `font-lock-turn-o-thing-lock`, is even worse.

I really don't see how the feature you want is possible at all, but if I'm missing something, I'd be happy to be corrected.

**Comment by oantolin** [comment]
Well, one thing that could be done is to just try! One could compute the set of matches for the longest common substring, and if it is the same as the current candidate set, then perform the replacement. When you are using `orderless-literal` or `orderless-regexp` as a matching style in the current completion session, this actually has some chance of working. Although, since I tend to match stuff from all over the candidate, I bet in my queries the longest common substring usually matches way more candidates. For example, if in `describe-function` I use `flo` as an initialism it matches the following:

- `find-lisp-object-file-name`
- `find-library-other-frame`
- `find-library-other-window`
- `font-lock-turn-off-thing-lock`
- `font-lock-turn-on-thing-lock`
- `frame-list-z-order`
- `x-frame-list-z-order`

The longest common substring is a single letter, I believe, so it matches way too much.

Then, if I want one of the `find-*` candidates I'd add `fi` to my query; `flo fi` matches just the first 3 in that list (`flo` as an initialism and `fi` literally). At that point the longest common substring is `find`, which still matches way too much.

---- 

Also, I just realized I don't understand the point of a feature like this. Replacing the input with the longest common substring is only valid if they match the same set of candidates, which means that by definition it makes 0 progress towards narrowing down to a single candidate. Can you explain why you want this?

**Comment by JSDurand** [comment]
First thanks for pointing out the problem with matching the candidates after the replacement. 

I admit that the situation I had in mind is too simplistic: I oft just use orderless-regex or orderless-literal to match. And the reason I consider this feature is because oft there are similarly named candidates. For example, if in `describe-function` one uses literal to match, and types "epa-li", then there are only two matches: "epa-list-keys" and "epa-list-secret-keys". And one cannot use the literal style to choose the candidate "epa-list-keys", since it is a substring of the other candidate, unless one types the whose string, which loses the purpose of completion, dare I say.

As an aside, I fed the strings in your example to my function, and it returns `'("-l" "-o")`, so there are actually two longest common substrings. And when you add `fi` to the query, the longest common substring is `"find-li"`. :-)

I see now that simply replacing the user input does not solve the problem. So I am thinking maybe there can be a way for the user to specify an action for `try-completions". Then the user can choose to add a "common part" of the candidates, however the user wants to extract that, into the user input, and to mark it with a special symbol which tells the user's style dispatcher to use the style "regex" or something else for that special part.

Thanks again for the valuable feedback.

**Comment by oantolin** [comment]
Oh, thanks for pointing out I calculated the longest common substrings wrong. Fortunately for my example, there are still too many things that match `find-li`.

> So I am thinking maybe there can be a way for the user to specify an action for `try-completions". Then the user can choose to add a "common part" of the candidates, however the user wants to extract that, into the user input, and to mark it with a special symbol which tells the user's style dispatcher to use the style "regex" or something else for that special part.

I think probably any feature along these lines is more complicated than its worth, and I don't think I'm likely to add it. Instead, let me offer a couple of workarounds for your issue:

1.  To get the behavior you want for when you've typed only one component (i.e., no spaces yet), you could use `(setq completion-styles '(substring orderless))`. Your `epa-li` example works perfectly with that setting. This may actual cover most of the cases where you want this behavior, give it a shot.
2. If you have some more behavior in mind also for multiple components, even if that behavior only works for your particular orderless configuration, it sounds like it might be easy for you to implement for yourself, now that you have that cool suffix-tree package. You could implement it as a standalone command that you bind to `TAB` in the minibuffer.

**Comment by JSDurand** [comment]
Thanks for the suggestions. Indeed the first suggestion perfectly solves the problem I had in mind, in most cases. Combined with the proposal of minad, this becomes even better.

OK, I shall try to see how things go with the trees. :-) Oh, and I have finished writing a function that returns the "maximal" common substring of multiple strings.

Thanks for the reply in any case. :)
