### ISSUE TITLE
For company popups, match with ^ automatically. Possible?

### ISSUE THREAD

**Issue by kenranunderscore** [oantolin/orderless#48]
I've recently started building an Emacs configuration myself instead of using some packaged solution, and I happily use `orderless`, it's awesome :)

Now that I've come the point where I want to program (again) in Emacs, I realized that orderless is used for those company popups as well (great!). Is there a way to make it so that when typing (in a scratch buffer, I tried typing `(macro` to see its hundreds of completions) the completions that are shown are interpreted as if I had actually typed `^myword`?

With the examples in the readme I'm pretty sure I could do that "globally" for orderless by adding a dispatcher, but I think I only want this behavior for those popups. Is there a nice way to do that?

(If this is the wrong place, I'm sorry)

**Comment by minad** [comment]
This is a very similar issue to #49.

**Comment by kenranunderscore** [comment]
@minad Phew, I don't really understand your issue all that well yet. Yours looks like a bug somewhere to me, while I don't see any obviously wrong completions in my case. I felt like mine is more a matter of knowing how to configure orderless.

Am I wrong here? I'm happy to learn more about this as I want to get into writing elisp myself. For instance the toy code you posted in #49 is a very cool example of how one would even debug this stuff :+1:

**Comment by minad** [comment]
@kenranunderscore Yes, #49 is a more intricate underlying issue about how some capf backends work. But I am not yet sure about how to resolve this.

* For once there is the problem that company usually stops completion as soon as you enter a space (https://github.com/oantolin/orderless/#company and #35). The problem is that the completion style does not have full control. 
* Then there is the issue that the results returned by capf may not match the input string (assume for example that the capf backend performs some kind of expansion of the prefix, but the expanded string does not match the original prefix). Then the completion style may filter out the candidates.
* Company always asks the capf backend for new candidates for every character you enter. This means the input string you enter must somehow be accepted by both the capf backend and the completion style. This is particularly problematic with lsp servers, which look directly at the buffer and return the candidates depending on the context around the point. This means one has to stop asking the server for candidates as soon as one wants to do completion style filtering. (This is a bit like the consult-grep command, where you have grep-filtering and completion-style filtering, if you are familiar with that command)

The question you are asking is valid. I hope I don't cause too much confusion here. You basically want the backend to see "prefix" and the completion style orderless to match "^prefix".

**Comment by minad** [comment]
@kenranunderscore You can use the following style dispatcher in order to add the caret for prefix matches to the first pattern.

~~~ elisp
(defun caret-orderless-dispatch (pattern index _total)
  (when (= index 0)
    `(orderless-regexp . ,(concat "^" pattern))))
(setq orderless-style-dispatchers '(caret-orderless-dispatch))
~~~

**Comment by oantolin** [comment]
You can probably also test in an orderless dispatcher whether company is active or not, but I don't know how to do that off the top of my head since I don't use company.

**Comment by minad** [comment]
@oantolin Yes, I am using something like this for Corfu where I check for `completion-in-region-mode`. Maybe in Company you can use the variable `company-my-keymap` to detect if Company is active. Sorry for the blurb above, this happened when I was thinking about how Corfu should work and how it should work with special backends like lsp/eglot.

**Comment by kenranunderscore** [comment]
Thank you for the answers!
@minad Your explanations piqued my interest in corfu and I'll be giving it a try instead of company (which accidentally also made me realize that the features of selectrum I use are basically vertico, so I switched there, too). First steps feel great and I think I might just like not having auto-completion pop up on its own, but rather when I wish it to.

But I'll stop derailing this ticket: I won't try anything here for the time being. Feel free to close if you like.

**Comment by iostapyshyn** [comment]
Just in case somebody has the same problem and is okay with not using `orderless` for company, here's what I use:

```elisp
(define-advice company-capf
    (:around (orig-fun &rest args) set-completion-styles)
  (let ((completion-styles '(basic partial-completion)))
    (apply orig-fun args)))
```

**Comment by kenranunderscore** [comment]
I'm also using @iostapyshyn's customization above and that suffices for me. Of course reopen if you'd like to keep this around as a marker/reminder or something.
