### ISSUE TITLE
Empty pattern should compile to empty regexp list

### ISSUE THREAD

**Issue by minad** [oantolin/orderless#55]
This optimization plays a role for consult-ripgrep as long as you only enter "#grep" without a filter expression. The speed up is noticeable with many candidates. Where can we add this optimization to the pattern compiler? Short-circuit on empty/white-space-only input strings?

**Comment by oantolin** [comment]
Oh my! I thought this already happened! I'll fix it.

It's just ridiculous:

```elisp
(orderless-pattern-compiler ""); => ("\\(?:\\)")
(orderless-pattern-compiler " "); => ("\\(?:\\)" "\\(?:\\)")
```

😆

**Comment by oantolin** [comment]
The problem is split-string:

```elisp
(split-string "" " +"); => ("")
(split-string " " " +"); => ("" "")
```

**Comment by oantolin** [comment]
How about just calling `split-string` with the `omit-nulls` parameter set to `t`? Do people really want these null components? I have a vague recollection of someone asking for null components...

But if people really, really want null components, they can set `orderless-component-separator` to a function which provides them.

**Comment by oantolin** [comment]
I'll omit empty components and wait to see if anyone misses them. If someone does miss them, I'll them to use a function for `orderless-component-separator` instead of a regexp.

**Comment by minad** [comment]
I see, thanks for the quick fix! There are still a few `consult-ripgrep` performance issues I hope to fix. Ultimately I believe it is hard to make `consult-ripgrep` as performant as `counsel-rg` since `counsel-rg` avoids some of the Emacs infrastructure. But I can at least try to fix some obvious performance problems, like this particular issue :)

**Comment by oantolin** [comment]
> I see, thanks for the quick fix!

I added a space and a `t`. I wish all issues were that easy. 😛

**Comment by oantolin** [comment]
Oh, I think I remember what the point of the empty components was! Someone (maybe @noctuid?) had a dispatcher that treated the first component as an initialism and the rest as literals, or something like that. Then an initial space would give you an empty initial component and you could match everything literally.

**Comment by minad** [comment]
> I added a space and a t. I wish all issues were that easy.

Indeed :)

> Then an initial space would give you an empty initial component and you could skip the initialism and match everything literally.

Is there a possibility to still cater for such a use case? But to me this feels a bit out of scope, since white space otherwise does not play a role in Orderless.

**Comment by oantolin** [comment]
> Is there a possibility to still cater for such a use case?

Absolutely: `(setq orderless-component-separator (lambda (str) (split-string str " +"))`, just use a function and don't pass `t`!

I don't use position-based dispatchers, but I think that if I did, maybe instead of a null component, I'd setup some special syntax for skipping a position, like `,`, which is pretty close to the spacebar.

**Comment by noctuid** [comment]
>  But to me this feels a bit out of scope, since white space otherwise does not play a role in Orderless.

The way I see it is that spaces separate the components, so by using a space at the beginning, I'm just skipping any rules I have for the first component. When using index-based rules, it's consistent whether or not I have a first component.

> Absolutely: (setq orderless-component-separator (lambda (str) (split-string str " +")), just use a function and don't pass t!

But then this has the same problem as before. Why not just use `nil` instead of the split-string result if it is just a list of empty strings? It's nice that I can implement this myself by setting `orderless-component-separator` to a function, but this seems like a sane default behavior to me.

**Comment by minad** [comment]
> The way I see it is that spaces separate the components, so by using a space at the beginning, I'm just skipping any rules I have for the first component.

Makes sense. For me it is only important that empty strings or only whitespace strings compile to an empty regexp list.

**Comment by oantolin** [comment]
Should we bring back the null components then? And special case the entire-input-is-whitespace case?

**Comment by noctuid** [comment]
That would be my preference, but it's not a huge deal either way since it's easy to get the behavior back:
```elisp
  (defun noct-split-orderless-component (str)
    (let ((components (split-string str "[ &]")))
      (when (remove "" components)
        components)))

(setq orderless-component-separator #'noct-split-orderless-component)
```

**Comment by jdtsmith** [comment]
Took me a long time to realize I miss null components, but I do, for LSP completion output with corfu and orderless.  Since the LSP server uses some unknown secret sauce to decide on relevant matches (many behave kind of like flex), you typically dispatch by term, such that the 1st component is preserved _exactly_.  Something like:

```elisp
(orderless-define-completion-style orderless-eglot
    "Let all server-provided candidates matching the first term through.
Note that \"\" as a replacment string matches anything."
    (orderless-style-dispatchers
     (cons (lambda (pattern index &rest r)
	     (and (eq index 0) '(orderless-literal .  ""))) 
	   orderless-style-dispatchers)))
```

Sometime you want to take _all_ possible candidates from the server, and immediately apply an orderless filter.  E.g.:

- `sys.[Tab]` → all server candidates pop-up
-  ` !foo` → remove the `foo` from them

This  used to work when providing a leading space in the pattern (long ago, apparently).  But now, with `OMIT-NULLS=t`, leading space is silently trimmed away, so there's no way to "skip the first component".  Note that corfu has a specific affordance for including a space separator without ending the completion popup, and with CAPE can be configured to dump the completion table frequently to give the server a chance to update the list of candidates.

Maybe it's been long enough that people are relying on this new null-omission behavior, in which case I can use a custom separator function like @noctuid did.  But I doubt it :).
