### ISSUE TITLE
Error in post-command-hook (vertico--exhibit): (void-function orderless-highlight-matches)

### ISSUE THREAD

**Issue by conao3** [oantolin/orderless#64]
cc: @minad (vertico author)

---

Thanks for your package!

I got `Error in post-command-hook (vertico--exhibit): (void-function orderless-highlight-matches)` and minibuffer doesn't work anyway...

## Repro steps

1. Save below snipet as `~/.debug.emacs.d/vertico-sample/init.el`
```elisp
;;; init.el --- Sample clean init.el  -*- lexical-binding: t; -*-

;; ~/.debug.emacs.d/orderless/init.el

;; you can run like 'emacs -q -l ~/.debug.emacs.d/orderless/init.el'
(let ((this-file (or (bound-and-true-p byte-compile-current-file)
                     load-file-name
                     buffer-file-name)))
  (setq user-emacs-directory
        (expand-file-name (file-name-directory this-file))))

(custom-set-variables
 '(package-archives '(("org"   . "https://orgmode.org/elpa/")
                      ("melpa" . "https://melpa.org/packages/")
                      ("gnu"   . "https://elpa.gnu.org/packages/"))))

(package-initialize)
(package-refresh-contents)

(setq debug-on-error t)

(unless (package-installed-p 'vertico)
  (package-install 'vertico))

(vertico-mode 1)

(unless (package-installed-p 'orderless)
  (package-install 'orderless))

(setq completion-styles '(orderless))
```
2. `cd ~/.debug.emacs.d/vertico-sample`
4. `rm -rf elpa && emacs -q -l ~/.debug.emacs.d/vertico-sample/init.el`
5. `C-x C-f` then press `e`.
6. see error like below scrrenshot (I cannot get stacktrace. Please tell me if you know how to get it)
![Screenshot_2021-06-26_14-32-06](https://user-images.githubusercontent.com/4703128/123511068-2486b080-d6ba-11eb-82e0-ac5b5a5f0091.png)

## Additional note 1
I have no idea but when I start Emacs again (with orderless and vertico installed), the minibuffer works fine.
1. `rm -rf elpa && emacs -q -l ~/.debug.emacs.d/vertico-sample/init.el`
2. `C-x C-f` then press `e`.
3. see the error.
4. `C-x C-c` to exit Emacs
5. `emacs -q -l ~/.debug.emacs.d/vertico-sample/init.el`
6. `C-x C-f` then press `e`.
7. Minibufer works well.

## Additional note 2
I have no idea too, but when I fix init.el like this (install `orderless` before enabling `vertico-mode`), minibuffer error has gone and works well.
```elisp
;;; init.el --- Sample clean init.el  -*- lexical-binding: t; -*-

;; ~/.debug.emacs.d/orderless/init.el

;; you can run like 'emacs -q -l ~/.debug.emacs.d/orderless/init.el'
(let ((this-file (or (bound-and-true-p byte-compile-current-file)
                     load-file-name
                     buffer-file-name)))
  (setq user-emacs-directory
        (expand-file-name (file-name-directory this-file))))

(custom-set-variables
 '(package-archives '(("org"   . "https://orgmode.org/elpa/")
                      ("melpa" . "https://melpa.org/packages/")
                      ("gnu"   . "https://elpa.gnu.org/packages/"))))

(package-initialize)
(package-refresh-contents)

(setq debug-on-error t)

(unless (package-installed-p 'vertico)
  (package-install 'vertico))
(unless (package-installed-p 'orderless)
  (package-install 'orderless))

(vertico-mode 1)
(setq completion-styles '(orderless))
```

**Comment by minad** [comment]
Yes, in case you want to use Orderless with Vertico, it is necessary to install Orderless before activating vertico-mode. Otherwise you will observe this load error. I haven't found a way to avoid this problem. At least this is not an Orderless issue, but purely the fault of Vertico (and similarly of Corfu).

See the problematic code here: https://github.com/minad/vertico/blob/27c72e6b90944239d6ac2510d34f91a6c3cb95da/vertico.el#L269-L273

**Comment by conao3** [comment]
Thanks @minad! and sorry @oantolin for an unrelated issue, ignore me.
Let's move to `vertico` issue board.

**Comment by minad** [comment]
I've already pushed a fix https://github.com/minad/vertico/commit/5ed4530dd354df0f46709fa66e2e117cceb56933.

The fix is not perfect however. With the fix, the very first run of Vertico will NOT enjoy optimized deferred highlighting. This happens when orderless has not been loaded yet, and will be loaded lazily by `completion-all-completions` at a time when the advices have already been installed. I don't think a perfect fix is possible, since we have a circular load order dependency here. But at least the user will not observe issues and after the first completion session everything will be fast.

My recommendation is to always require orderless such that it is already loaded when vertico runs for the first time.

**Comment by conao3** [comment]
Thanks for that quick fix! I try that.
