### ISSUE TITLE
Issue completing ssh hostnames when using orderless

### ISSUE THREAD

**Issue by plattfot** [oantolin/orderless#67]
When using `orderless` and `find-file` and I type `/ssh:`, the completions I get are `/scp:` and `/scpx:`, expected to see a list of hostnames prefixed with `/ssh:`.

# Repro
## Versions
`orderless-0.6`
`emacs-28.0.50`
## Steps

Create `/tmp/init.el` containing:
```
(require 'orderless)
(setf completion-styles '(orderless))
```
Run `emacs -Q -l /tmp/init.el` and call `find-file` and type `/ssh:` and press tab. It should just give `/scp:` and `/scpx:` as completions.

Run `emacs -Q` do the same and you should see a list of known hosts.

**Comment by minad** [comment]
*Copying my comment from https://github.com/minad/vertico/issues/68*:

It seems that only the `basic` completion style shows hostnames. My recommendation is to define a special completion style `orderless-remote` which falls back to `basic` for remote completion:

~~~ elisp
(defun orderless-remote-try-completion (string table pred point)
  (if (string-match-p "\\`/[^/|:]+:" (substitute-in-file-name string))
      (or (completion-basic-try-completion string table pred point)
          (orderless-try-completion string table pred point))
    (orderless-try-completion string table pred point)))

(defun orderless-remote-all-completions (string table pred point)
  (if (string-match-p "\\`/[^/|:]+:" (substitute-in-file-name string))
      (or (completion-basic-all-completions string table pred point)
          (orderless-all-completions string table pred point))
    (orderless-all-completions string table pred point)))

(add-to-list
 'completion-styles-alist
 '(orderless-remote orderless-remote-try-completion orderless-remote-all-completions nil))

(setq completion-category-overrides '((file (styles orderless-remote))))
~~~

Alternatively you can just define to use `basic` in combination with `orderless`, but this may be undesired, since it will affect every file completion, not only remote files.

~~~ elisp
(setq completion-category-overrides '((file (styles basic orderless))))
~~~

**Comment by minad** [comment]
Note that `substring` also does not support host name completion. It is really required to use `basic` for this to work.

Related issues with dynamic tables, which do not work with `substring` or `orderless`: #45, #20

**Comment by plattfot** [comment]
Thanks @minad! I'm using the special completion style `basic-remote` and works perfectly for me.

I'm closing this issue as this solves my issue.

**Comment by oantolin** [comment]
Thanks @minad!
