### ISSUE TITLE
Freezing when find-file in a directory containing a bad mountpoint

### ISSUE THREAD

**Issue by jackkamm** [oantolin/orderless#75]
Today, on the HPC cluster I work on, I noticed that Emacs would freeze up when using `find-file` with `icomplete-mode` and completion-style `orderless`. The issue seems to be due to a bad mountpoint in the directory I called `find-file` with.

Here's the scenario. My home directory has a symlink `~/bad-mountpoint -> /path/to/bad-mountpoint`, where `/path/to/bad-mountpoint` is some sort of network share. Today, something went wrong with that mountpoint, so that when I call `ls /path/to/bad-mountpoint` in the shell, the command hangs until I interrupt it Control+C.

Now, in Emacs, when I do `C-x C-f` in my home directory, Emacs freezes and I'm unable to recover. However, when I switch `completion-styles` back to the default value (without `orderless`), then Emacs works fine again.

If I remove the bad symlink in my home directory, then using the orderless completion style works again.

I was wondering if you had insight into what might cause this, or whether there's anything that can be done to make orderless more robust to this situation.

Sorry if this is somewhat vague. As I mentioned above, this is on an HPC cluster, where I don't have any admin powers, and I don't know all the details of how the sysadmins have set up mount points and network shares. So it's a little tricky to troubleshoot this.

**Comment by minad** [comment]
> I was wondering if you had insight into what might cause this, or whether there's anything that can be done to make orderless more robust to this situation.

Most likely we cannot do anything in Orderless about this, since Orderless is only the filter (completion style), which is not aware of the type of the underlying candidates. Orderless only filters the strings - there is nothing there which should hang. You will probably also see the hanging behavior if you use other completion styles.

I recommend to instead ask on the discussion board of your completion UI about this, for example the [Vertico discussion page](https://github.com/minad/vertico/discussions), if you use Vertico. However in order to investigate, a reproducible recipe would be needed. Maybe you can reproduce this with sshfs, after then disconnecting the network?
